### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by andybondar** [Arina-Zap/devops-course-task6c-terraform#2]
Hi,

I created a pull request suggesting some improvements to your Terraform code:
https://github.com/Arina-Zap/devops-course-task6c-terraform/pull/1

Please review it and read the `README.md` file here:
https://github.com/andybondar/devops-course-task6c-terraform/tree/feature/conventinal-module-structure

If you like the improvements, feel free to merge them into the main branch in your repository.
If you have any questions, please let me know.

**Comment by Arina-Zap** [comment]
Thank you for your help and improvements to my code!
